#!/usr/bin/env bash
# check-qg-conf-drift.sh — verify tools/qg.conf is in sync with .dev/stack.yml.
#
# qg.conf is a GENERATED file: /release-setup renders it from stack.yml's
# quality_gates block (dev-core release-setup cookbook, step N4a). It is committed
# but was never enforced → it can rot silently (bump stack.yml max_lines or flip the
# metric without re-running /release-setup and the gates keep using the stale config).
# This gate regenerates qg.conf to a temp file using the SAME logic as N4a and diffs
# it against the committed copy. stack.yml is the single source of truth.
#
# COUPLING: the generation block below mirrors cookbook N4a verbatim, INCLUDING the
# runtime+metric → EXTS/COUNTER derivation table. QG_*_ROOT is fixed to src/ there
# (not yet derived from globs). If N4a changes, update this script to match or it
# will emit false drift.
#
# Exit-code contract (mirrors scripts/check-acl-specs-drift.sh):
#   0 = clean (no drift)
#   1 = drift detected (qg.conf differs from freshly rendered output, or is missing)
#   2 = generator crash (yaml parse failed / uv unavailable)
#
# To fix drift locally: run /release-setup --force (regenerates qg.conf), or
# hand-sync tools/qg.conf to .dev/stack.yml, then commit the result.
#
# Usage: bash scripts/check-qg-conf-drift.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

STACK="${REPO_ROOT}/.dev/stack.yml"
QG_COMMITTED="${REPO_ROOT}/tools/qg.conf"

# No stack.yml → nothing to check against. Skip with warning, not false-green silence.
if [ ! -f "$STACK" ]; then
    echo "WARN: $STACK not found, skipping check-qg-conf-drift" >&2
    exit 0
fi

TMPDIR_GATE=$(mktemp -d)
trap 'rm -rf "$TMPDIR_GATE"' EXIT
QG_FRESH="${TMPDIR_GATE}/qg.conf"

# Derive thresholds + paths from stack.yml — identical to release-setup cookbook N4a.
FILE_MAX=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print((d.get('quality_gates',{}).get('file_length',{}) or {}).get('max_lines',300))") || exit 2
FOLDER_MAX=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print((d.get('quality_gates',{}).get('folder_size',{}) or {}).get('max_files',12))") || exit 2
FILE_EX=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print((d.get('quality_gates',{}).get('file_length',{}) or {}).get('exemptions_file','tools/file_exemptions.txt'))") || exit 2
FOLDER_EX=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print((d.get('quality_gates',{}).get('folder_size',{}) or {}).get('exemptions_file','tools/folder_exemptions.txt'))") || exit 2

# SLOC metric: read metric from stack.yml; derive EXTS + COUNTER from runtime + metric (N4a table).
RUNTIME=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print(d.get('runtime','python'))") || exit 2
FILE_METRIC=$(uv run python -c "import yaml; d=yaml.safe_load(open('.dev/stack.yml')); print((d.get('quality_gates',{}).get('file_length',{}) or {}).get('metric','raw'))") || exit 2

if [ "$RUNTIME" = "node" ]; then
    FILE_EXTS="js jsx ts tsx"
    if [ "$FILE_METRIC" = "sloc" ]; then FILE_COUNTER="sloc-npm"; else FILE_COUNTER="wc"; fi
else
    FILE_EXTS="py"
    if [ "$FILE_METRIC" = "sloc" ]; then FILE_COUNTER="radon"; else FILE_COUNTER="wc"; fi
fi

cat > "$QG_FRESH" <<EOF
# Generated by /release-setup — do not edit directly. Edit .dev/stack.yml instead.
QG_FILE_MAX=${FILE_MAX}
QG_FOLDER_MAX=${FOLDER_MAX}
QG_FILE_ROOT=src/
QG_FOLDER_ROOT=src/
QG_FILE_EXEMPTIONS=${FILE_EX}
QG_FOLDER_EXEMPTIONS=${FOLDER_EX}
QG_FILE_METRIC=${FILE_METRIC}
QG_FILE_EXTS="${FILE_EXTS}"
QG_FILE_COUNTER=${FILE_COUNTER}
EOF

if [ ! -f "$QG_COMMITTED" ]; then
    echo "::error::tools/qg.conf is missing but .dev/stack.yml defines quality_gates. Run /release-setup --force and commit qg.conf." >&2
    exit 1
fi

if ! diff -u "$QG_COMMITTED" "$QG_FRESH"; then
    echo "::error::tools/qg.conf is stale vs .dev/stack.yml. Run /release-setup --force (or hand-sync) and commit the result." >&2
    exit 1
fi

echo "✓ tools/qg.conf matches .dev/stack.yml quality_gates"
